// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVl8v2_gZa5netCVfnBSSfmrGnPpSePyM',
    appId: '1:118126850278:web:0a69b4fb350b23adbc0b27',
    messagingSenderId: '118126850278',
    projectId: 'emit-82f81',
    authDomain: 'emit-82f81.firebaseapp.com',
    storageBucket: 'emit-82f81.appspot.com',
    measurementId: 'G-W4HFQR34JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5RR83-4ptVIYAL2TkyRkvyJQH1vM8A6A',
    appId: '1:118126850278:android:28740291ce57611bbc0b27',
    messagingSenderId: '118126850278',
    projectId: 'emit-82f81',
    storageBucket: 'emit-82f81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRG6m5MyrjCnZwlBR2FNZ1LxPsLOJeoVA',
    appId: '1:118126850278:ios:74fde1a2d9d7b07abc0b27',
    messagingSenderId: '118126850278',
    projectId: 'emit-82f81',
    storageBucket: 'emit-82f81.appspot.com',
    iosBundleId: 'otek.technologies.emitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRG6m5MyrjCnZwlBR2FNZ1LxPsLOJeoVA',
    appId: '1:118126850278:ios:cced0ad899bef941bc0b27',
    messagingSenderId: '118126850278',
    projectId: 'emit-82f81',
    storageBucket: 'emit-82f81.appspot.com',
    iosBundleId: 'otek.technologies.emitApp.RunnerTests',
  );
}
